// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/karp.proto

package karp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Karp_Consume_FullMethodName = "/Karp/Consume"
)

// KarpClient is the client API for Karp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KarpClient interface {
	Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Ack, Message], error)
}

type karpClient struct {
	cc grpc.ClientConnInterface
}

func NewKarpClient(cc grpc.ClientConnInterface) KarpClient {
	return &karpClient{cc}
}

func (c *karpClient) Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Ack, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Karp_ServiceDesc.Streams[0], Karp_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Ack, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Karp_ConsumeClient = grpc.BidiStreamingClient[Ack, Message]

// KarpServer is the server API for Karp service.
// All implementations must embed UnimplementedKarpServer
// for forward compatibility.
type KarpServer interface {
	Consume(grpc.BidiStreamingServer[Ack, Message]) error
	mustEmbedUnimplementedKarpServer()
}

// UnimplementedKarpServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKarpServer struct{}

func (UnimplementedKarpServer) Consume(grpc.BidiStreamingServer[Ack, Message]) error {
	return status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedKarpServer) mustEmbedUnimplementedKarpServer() {}
func (UnimplementedKarpServer) testEmbeddedByValue()              {}

// UnsafeKarpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KarpServer will
// result in compilation errors.
type UnsafeKarpServer interface {
	mustEmbedUnimplementedKarpServer()
}

func RegisterKarpServer(s grpc.ServiceRegistrar, srv KarpServer) {
	// If the following call pancis, it indicates UnimplementedKarpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Karp_ServiceDesc, srv)
}

func _Karp_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KarpServer).Consume(&grpc.GenericServerStream[Ack, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Karp_ConsumeServer = grpc.BidiStreamingServer[Ack, Message]

// Karp_ServiceDesc is the grpc.ServiceDesc for Karp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Karp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Karp",
	HandlerType: (*KarpServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _Karp_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/karp.proto",
}
